//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int idCliente { get; set; }
        public string nombreCliente { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    }
}
